name: tp_charts
description: Beautiful animated chart widgets for Flutter with customizable styling. Includes CustomLineChart (with built-in filters), SimpleLineChart (external filtering), and HotChart (gauge-style).
version: 1.1.0
homepage: https://github.com/pradoui/tp_charts
repository: https://github.com/pradoui/tp_charts
issue_tracker: https://github.com/pradoui/tp_charts/issues
documentation: https://github.com/pradoui/tp_charts#readme

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
